============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/snehashish/regression_project
collected 4 items

test_regression_project.py ..F.                                          [100%]

=================================== FAILURES ===================================
________________________ test_regression_model_training ________________________

regression_data = (array([[5.48813504e-01],
       [7.15189366e-01],
       [6.02763376e-01],
       [5.44883183e-01],
       [4.2365479...2.51379489],
       [1.19438701],
       [1.85012794],
       [2.79659873],
       [1.47661446],
       [2.4840165 ]]))
regression_model = <keras.src.engine.sequential.Sequential object at 0x7fad2b29ae90>

    def test_regression_model_training(regression_data, regression_model):
        X_train, y_train = regression_data
        loss = regression_model.evaluate(X_train, y_train)
>       assert loss < 0.1  # Adjust as needed
E       assert 3.6115217208862305 < 0.1

test_regression_project.py:32: AssertionError
---------------------------- Captured stdout setup -----------------------------
 1/32 [..............................] - ETA: 5s - loss: 4.001132/32 [==============================] - 0s 869us/step - loss: 3.7086
----------------------------- Captured stdout call -----------------------------
 1/32 [..............................] - ETA: 1s - loss: 4.055332/32 [==============================] - 0s 785us/step - loss: 3.6115
=========================== short test summary info ============================
FAILED test_regression_project.py::test_regression_model_training - assert 3....
========================= 1 failed, 3 passed in 1.32s ==========================
